### ISSUE TITLE
Live demo/example

### ISSUE THREAD

**Issue by lafkpages** [Hugoonreplit/Chess.css#1]
Hey there Hugito,

It would be great to have a live demo on Replit to see how the stylesheet actually looks.
Maybe some screenshots in the README as well.

**EDIT**: I see a demo page on the About section, but it's tiny and barely noticeable, can't you just add that link to the README or add screenshots?

Gracias

**Comment by Hugoonreplit** [comment]
Hey there Luisito,

thanks for putting this as an issue, it's currently being worked on!

Gracias
